# Generated by Django 2.0.7 on 2020-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_two',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
    ]
