# Generated by Django 2.0.7 on 2020-01-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_user_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_two',
            name='password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user_two',
            name='username',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
